### ISSUE TITLE
Can't join a game with lobby members using Multiplayer\Xbox\ example

### ISSUE THREAD

**Issue by whiteeat** [Microsoft/xbox-live-samples#59]
We are using XDKS.1 Sandbox and using developer accounts with gold membership. Then, one account start the example then invite a friend, and the friend can receive the invite and correctly join the same lobby session. It's correctly displayed that two users are in the same lobby session. However, when the lobby host press button A to join the game, it only shows the host joins the game on the UI on host console, and nothing happens on another console. So do you guys have any ideas what is happening? Thanks!

**Comment by adityatMS** [comment]
That is by design. Each client that wants to join the game, needs to call join_game_from_lobby. In terms of the sample, each client will need to select 'A' to join the game. However, if a game is already in progress, then any new friend that joins the lobby will auto join into the game, if a game session exists and if there is room.
